### ISSUE TITLE
vignette("phaseR") does not work

### ISSUE THREAD

**Issue by tomicapretto** [mjg211/phaseR#11]
Just a (self?) reminder that `vignette("phaseR")`, as suggested in `?phaseR`, does not work. 
The call that work is `vignette("my-vignette", package = "phaseR")`

**Comment by mjg211** [comment]
Thanks, have been meaning to fix this for a while! Changed to `vignette("introduction", package = "phaseR")` in anticipation of adding other vignettes soon.
