### ISSUE TITLE
Package is removed from CRAN?

### ISSUE THREAD

**Issue by burgerga** [mjg211/phaseR#6]
Running into the problem that students can't use phaseR anymore.

https://cran.r-project.org/web/packages/phaseR/index.html

> Archived on 2019-09-08 as check problems were not corrected in time.

Time to get that `.travis.yml` to work ;)

**Comment by burgerga** [comment]
Problem might be related to `deSolve`, workaround for the time being:

```r
install.packages('deSolve')
remotes::install_github("mjg211/phaseR")
```

**Comment by mjg211** [comment]
Will fix this ASAP!

**Comment by mjg211** [comment]
Have submitted a new version with a fix, hopefully up on CRAN soon :)

**Comment by mjg211** [comment]
It passed; should be back up soon
